core/urls.py
from django.urls import path

from core.views import (
    home_view,
    about_us_view,
    contact_us_view,

    services_view,
    projects_view,
    # quote_view,
    # team_view,
    # features_view, 
)

app_name = "core"
urlpatterns = [
    path("", home_view, name="home"),
    path("about-us/", about_us_view, name="about_us"),
    path("services/", services_view, name="services"),
    path("contact-us/", contact_us_view, name="contact_us"),
    path("projects/", projects_view, name="projects"),

    # path("team/", team_view, name="team"),
    # path("features/", features_view, name="features"),
    # path("quote/", quote_view, name="quote"),
]

gct_energy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models


# Create your models here.
class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class CarouselImage(TimeStampedModel):
    title = models.CharField(max_length=255, verbose_name="Image Title")
    description = models.TextField(verbose_name="Image Description")
    image = models.ImageField(upload_to="carousel/", verbose_name="Carousel Image")

    def __str__(self):
        return self.title


class BrandStats(TimeStampedModel):
    happy_customers = models.IntegerField(verbose_name="Happy Customers")
    projects_completed = models.IntegerField(verbose_name="Projects Completed")
    awards_won = models.IntegerField(verbose_name="Awards Won")
    expert_workers = models.IntegerField(verbose_name="Expert Workers")

    def __str__(self):
        return "Brand Stats"


class Testimonial(TimeStampedModel):
    name = models.CharField(max_length=255, verbose_name="Full Name")
    content = models.TextField(verbose_name="Testimonial content")
    profession = models.CharField(max_length=255, verbose_name="Profession")
    image = models.ImageField(upload_to="testimonials/", verbose_name="Avatar Image")

    def __str__(self):
        return self.name


class TeamMember(TimeStampedModel):
    full_name = models.CharField(max_length=255, verbose_name="Full Name")
    profession = models.CharField(max_length=255, verbose_name="Profession")
    image = models.ImageField(upload_to="team/", verbose_name="Avatar Image")
    facebook = models.URLField(verbose_name="Facebook URL", blank=True, null=True)
    twitter = models.URLField(verbose_name="Twitter URL", blank=True, null=True)
    linkedin = models.URLField(verbose_name="LinkedIn URL", blank=True, null=True)

    def __str__(self):
        return self.full_name

core/views.py
from django.shortcuts import render


# Create your views here.
def home_view(request):
    context = {
        "title": "GCT Energy"
    }
    return render(request, "theme/pages/home.html", context=context)


def about_us_view(request):
    context = {
        "title": "About Us"

    }
    return render(request, "theme/pages/about_us.html", context=context)


def contact_us_view(request):
    context = {
        "title": "Contact Us"
    }
    return render(request, "theme/pages/contact_us.html", context=context)


def services_view(request):
    context = {
        "title": "Services"
    }
    return render(request, "theme/pages/services.html", context=context)


def projects_view(request):
    context = {
        "title": "Projects"
    }
    return render(request, "theme/pages/projects.html", context=context)

# def quote_view(request):
#     return render(request, "theme/pages/quote.html")
# def team_view(request):
#     return render(request, "theme/pages/team.html")
#
#
# def features_view(request):
#     return render(request, "theme/pages/features.html")

templates/theme/archived/features.html
{% extends 'theme/base.html' %}
{% block content %}
    {% include 'theme/widgets/breadcrumb.html' %}
    {% include 'theme/widgets/stats.html' %}
{% endblock content %}

templates/theme/archived/quote.html
{% extends 'theme/base.html' %}
{% block content %}

    {% include 'theme/widgets/breadcrumb.html' %}

    <!-- Quote Start -->
    <div class="container-fluid bg-light overflow-hidden px-lg-0" style="margin: 6rem 0;">
        <div class="container quote px-lg-0">
            <div class="row g-0 mx-lg-0">
                <div class="col-lg-6 ps-lg-0 wow fadeIn" data-wow-delay="0.1s" style="min-height: 400px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute img-fluid w-100 h-100" src="img/quote.jpg"
                             style="object-fit: cover;" alt="">
                    </div>
                </div>
                <div class="col-lg-6 quote-text py-5 wow fadeIn" data-wow-delay="0.5s">
                    <div class="p-lg-5 pe-lg-0">
                        <h6 class="text-primary">Free Quote</h6>
                        <h1 class="mb-4">Get A Free Quote</h1>
                        <p class="mb-4 pb-2">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam
                            amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo erat
                            amet</p>
                        <form>
                            <div class="row g-3">
                                <div class="col-12 col-sm-6">
                                    <input type="text" class="form-control border-0" placeholder="Your Name"
                                           style="height: 55px;">
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input type="email" class="form-control border-0" placeholder="Your Email"
                                           style="height: 55px;">
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input type="text" class="form-control border-0" placeholder="Your Mobile"
                                           style="height: 55px;">
                                </div>
                                <div class="col-12 col-sm-6">
                                    <select class="form-select border-0" style="height: 55px;">
                                        <option selected>Select A Service</option>
                                        <option value="1">Service 1</option>
                                        <option value="2">Service 2</option>
                                        <option value="3">Service 3</option>
                                    </select>
                                </div>
                                <div class="col-12">
                                    <textarea class="form-control border-0" placeholder="Special Note"></textarea>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-primary rounded-pill py-3 px-5" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Quote End -->
{% endblock content %}

templates/theme/archived/team.html
{% extends 'theme/base.html' %}
{% block content %}
    <!-- Page Header Start -->
    {% include 'theme/widgets/breadcrumb.html' %}
    <!-- Page Header End -->


    <!-- Team Start -->
    {% include 'theme/widgets/team_members.html' %}
    <!-- Team End -->
{% endblock content %}

templates/theme/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <link href="img/favicon.ico" rel="icon">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&family=Roboto:wght@500;700;900&display=swap"
          rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <link href="{% static 'css/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/owlcarousel/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/lightbox/lightbox.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<div id="spinner"
     class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

{% include 'theme/includes/header.html' %}

{% block content %}
{% endblock content %}

{% include 'theme/includes/footer.html' %}

<a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script src="{% static 'js/libs/wow/wow.min.js' %}"></script>
<script src="{% static 'js/libs/easing/easing.min.js' %}"></script>
<script src="{% static 'js/libs/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'js/libs/counterup/counterup.min.js' %}"></script>
<script src="{% static 'js/libs/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/libs/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/libs/lightbox/js/lightbox.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/theme/includes/footer.html
{% load static %}
<div class="container-fluid bg-dark text-body footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-4 col-md-6">
                <h5 class="text-white mb-4">Address</h5>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Koco Racin, bul. 12 Gevgelija</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-square btn-outline-light btn-social" href=""><i
                            class="fab fa-twitter"></i></a>
                    <a class="btn btn-square btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-square btn-outline-light btn-social" href=""><i
                            class="fab fa-youtube"></i></a>
                    <a class="btn btn-square btn-outline-light btn-social" href=""><i
                            class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <h5 class="text-white mb-4">Quick Links</h5>
                <a class="btn btn-link" href="{% url 'core:about_us' %}">About Us</a>
                <a class="btn btn-link" href="{% url 'core:contact_us' %}">Contact Us</a>
                <a class="btn btn-link" href="{% url 'core:services' %}">Our Services</a>
            </div>
            <div class="col-lg-4 col-md-6">
                <h5 class="text-white mb-4">Енергетска регулатива</h5>
                <a target="_blank" class="btn btn-link" href="{% static 'documents/zakon-za-energetika.pdf' %}">Закон за
                    енергетика</a>
                <a target="_blank" class="btn btn-link"
                   href="{% static 'documents/pravila-za-pazar-na-elektricna-energija.pdf' %}">Правила
                    за пазар</a>
                <a target="_blank" class="btn btn-link"
                   href="{% static 'documents/pravila-za-snabduvanje-so-elektricna-energija.pdf' %}">Правила за
                    снабдување</a>
                <a target="_blank" class="btn btn-link"
                   href="https://erc.org.mk/">Регулаторна комисија (Regulatory Commission)</a>
                <a target="_blank" class="btn btn-link"
                   href="https://www.memo.mk/">Маркет оператор</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a href="#">GCT Energy</a>, All Right Reserved.
                </div>
            </div>
        </div>
    </div>
</div>

templates/theme/includes/header.html
{% load static %}
<!-- Topbar Start -->
<div class="container-fluid bg-dark p-0">
    <div class="row gx-0 d-none d-lg-flex">
        <div class="col-lg-7 px-5 text-start">
            <div class="h-100 d-inline-flex align-items-center me-4 py-2">
                <small class="fa fa-map-marker-alt text-primary me-2"></small>
                <small>Koco Racin, bul. 12 Gevgelija</small>
            </div>
            {#            <div class="h-100 d-inline-flex align-items-center">#}
            {#                <small class="far fa-clock text-primary me-2"></small>#}
            {#                <small>Mon - Fri : 09.00 AM - 09.00 PM</small>#}
            {#            </div>#}
        </div>
        {#        <div class="col-lg-5 px-5 text-end">#}
        {#            <div class="h-100 d-inline-flex align-items-center me-4">#}
        {#                <small class="fa fa-phone-alt text-primary me-2"></small>#}
        {#                <small>+012 345 6789</small>#}
        {#            </div>#}
        {#            <div class="h-100 d-inline-flex align-items-center mx-n2">#}
        {#                <a class="btn btn-square btn-link rounded-0 border-0 border-end border-secondary" href=""><i#}
        {#                        class="fab fa-facebook-f"></i></a>#}
        {#                <a class="btn btn-square btn-link rounded-0 border-0 border-end border-secondary" href=""><i#}
        {#                        class="fab fa-twitter"></i></a>#}
        {#                <a class="btn btn-square btn-link rounded-0 border-0 border-end border-secondary" href=""><i#}
        {#                        class="fab fa-linkedin-in"></i></a>#}
        {#                <a class="btn btn-square btn-link rounded-0" href=""><i class="fab fa-instagram"></i></a>#}
        {#            </div>#}
        {#        </div>#}
    </div>
</div>
<!-- Topbar End -->


<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0">
    <a href="{% url 'core:home' %}" class="navbar-brand d-flex align-items-center border-end px-4 px-lg-5">
        <img class="m-0 text-primary" src="{% static 'brand/logo2.png' %}" alt="Logo"/>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            {% url 'core:home' as home_url %}
            <a href="{{ home_url }}"
               class="nav-item nav-link {% if request.path == home_url %}active{% endif %}">Home</a>
            {% url 'core:about_us' as about_us_url %}
            <a href="{{ about_us_url }}"
               class="nav-item nav-link {% if request.path == about_us_url %}active{% endif %}">About us</a>
            {% url 'core:services' as services_url %}
            <a href="{{ services_url }}"
               class="nav-item nav-link {% if request.path == services_url %}active{% endif %}">Services</a>
            {% url 'core:projects' as projects_url %}
            <a href="{{ projects_url }}"
               class="nav-item nav-link {% if request.path == projects_url %}active{% endif %}">Portfolio</a>
            <a href="{% url 'core:contact_us' %}" class="nav-item nav-link d-lg-none fw-bolder">Contact
                us<i
                        class="fa fa-arrow-right ms-3"></i></a>
        </div>
    </div>
    <a href="{% url 'core:contact_us' %}" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block">Contact
        us<i
                class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>
<!-- Navbar End -->

templates/theme/pages/about_us.html
{% extends 'theme/base.html' %}
{% block content %}

    {% include 'theme/widgets/breadcrumb.html' with breadcrumb_text="About us" %}

    {% include 'theme/widgets/about_us.html' %}
{% endblock content %}

templates/theme/pages/contact_us.html
{% extends 'theme/base.html' %}
{% block content %}
    {% include 'theme/widgets/breadcrumb.html' with breadcrumb_text="Contact us" %}

    <div class="container-fluid bg-light overflow-hidden px-lg-0" style="margin: 6rem 0;">
        <div class="container contact px-lg-0">
            <div class="row g-0 mx-lg-0">
                <div class="col-lg-6 contact-text py-5 wow fadeIn" data-wow-delay="0.5s">
                    <div class="p-lg-5 ps-lg-0">
                        <h6 class="text-primary">Contact Us</h6>
                        <h1 class="mb-4">Feel Free To Contact Us</h1>
                        <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti eum hic
                            incidunt iure molestias nisi non officiis placeat quia sed?Lorem ipsum dolor sit amet,
                            consectetur adipisicing elit. Ex, illo?Lorem ipsum dolor sit amet, consectetur adipisicing
                            elit. Adipisci, culpa earum facere fuga hic inventore magnam magni molestiae natus neque
                            nobis, non odio pariatur perferendis rem repellendus saepe similique veniam. </p>
                        <form>
                            <div class="row g-3">
                                <div class="col-md-6">
                                    <div class="form-floating">
                                        <input type="text" class="form-control" id="name" placeholder="Your Name">
                                        <label for="name">Your Name</label>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-floating">
                                        <input type="email" class="form-control" id="email" placeholder="Your Email">
                                        <label for="email">Your Email</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating">
                                        <input type="text" class="form-control" id="subject" placeholder="Subject">
                                        <label for="subject">Subject</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating">
                                    <textarea class="form-control" placeholder="Leave a message here" id="message"
                                              style="height: 100px"></textarea>
                                        <label for="message">Message</label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-primary rounded-pill py-3 px-5" type="submit">Send Message
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-6 pe-lg-0" style="min-height: 400px;">
                    <div class="position-relative h-100">

                        <iframe class="position-absolute w-100 h-100" style="object-fit: cover;"
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2964.816047683417!2d21.389136877275202!3d42.004223257506446!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1354146e17dd809b%3A0x7741a9cfe3c98a55!2sSkopje%20City%20Mall!5e0!3m2!1sen!2smk!4v1720992743292!5m2!1sen!2smk"
                                frameborder="0" allowfullscreen="" aria-hidden="false"
                                tabindex="0"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/theme/pages/home.html
{% extends 'theme/base.html' %}
{% block content %}
    {% include 'theme/widgets/carousel.html' %}
    {% include 'theme/widgets/about_us.html' %}
    {% include 'theme/widgets/services.html' %}
{% endblock content %}

templates/theme/pages/projects.html
{% extends 'theme/base.html' %}
{% block content %}
    {% include 'theme/widgets/breadcrumb.html' with breadcrumb_text="Our projects" %}
    <div class="container-fluid overflow-hidden my-5 ">
        <div class="container">
            <div class="row p-5">
                <p>GCT’s portfolio is increasing month by month.
                    We operate with 20+ clients where we have aggregated renewable energy sources that provide reliable
                    and stable energy supply, with best market prices.
                    Support their energy transition to renewable energy sources and therefore together we can influence
                    and contribute to a more eco-friendly and healthy living environment.
                </p>
            </div>
        </div>
    </div>
{% endblock content %}

templates/theme/pages/services.html
{% extends 'theme/base.html' %}
{% block content %}
    {% include 'theme/widgets/breadcrumb.html' with breadcrumb_text="Our services" %}
    {% include 'theme/widgets/services.html' %}
{% endblock content %}

templates/theme/widgets/about_us.html
{% load static %}
<div class="container-fluid bg-light overflow-hidden my-5 px-lg-0">
    <div class="container about px-lg-0">
        <div class="row g-0 mx-lg-0">
            <div class="col-lg-6 ps-lg-0 wow fadeIn" data-wow-delay="0.1s" style="min-height: 400px;">
                <div class="position-relative h-100">
                    <img class="position-absolute img-fluid w-100 h-100" src="{% static 'brand/about.jpg' %}"
                         style="object-fit: cover;" alt="">
                </div>
            </div>
            <div class="col-lg-6 about-text py-5 wow fadeIn" data-wow-delay="0.5s">
                <div class="p-lg-5 pe-lg-0">
                    <h6 class="text-primary">About Us</h6>
                    <h1 class="mb-4">GREENCORE TRADE(GCT)</h1>
                    <p>GREENCORE TRADE(GCT) is a company focused on the market distribution of electricity generated
                        from renewable energy sources.
                        With the electricity market constantly evolving due
                        to the growing share of distributed generation, there is notable volatility in
                        production and pricing across energy systems. As an aggregator for renewable sources
                        and controllable consumption, GCT offers renewable energy producers a dependable and expert
                        pathway to accessing energy markets.</p>
                    {#                    <p><i class="fa fa-check-circle text-primary me-3"></i>Diam dolor diam ipsum</p>#}
                    {#                    <p><i class="fa fa-check-circle text-primary me-3"></i>Aliqu diam amet diam et eos</p>#}
                    {#                    <p><i class="fa fa-check-circle text-primary me-3"></i>Tempor erat elitr rebum at clita</p>#}
                    <a href="{% url 'core:contact_us' %}" class="btn btn-primary rounded-pill py-3 px-5 mt-3">Contact
                        us</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/theme/widgets/breadcrumb.html
<div class="container-fluid page-header py-5 mb-5">
    <div class="container py-5">
        <h1 class="display-3 text-white mb-3 animated slideInDown">{{ breadcrumb_text }}</h1>

    </div>
</div>

templates/theme/widgets/carousel.html
<div class="container-fluid p-0 pb-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="owl-carousel header-carousel position-relative">
        {% for slide in carousel_images %}
            <div class="owl-carousel-item position-relative" data-dot="<img src='{{ slide.image.url }}'>">
                <img class="img-fluid" src="{{ slide.image.url }}" alt="">
                <div class="owl-carousel-inner">
                    <div class="container">
                        <div class="row justify-content-start">
                            <div class="col-10 col-lg-8">
                                <h1 class="display-2 text-white animated slideInDown">{{ slide.title }}</h1>
                                <p class="fs-5 fw-medium text-white mb-4 pb-3">{{ slide.description }}</p>
                                {#                                <a href="" class="btn btn-primary rounded-pill py-3 px-5 animated slideInLeft">Read#}
                                {#                                    More</a>#}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/theme/widgets/features.html
{% load static %}
<div class="container-fluid bg-light overflow-hidden my-5 px-lg-0">
    <div class="container feature px-lg-0">
        <div class="row g-0 mx-lg-0">
            <div class="col-lg-6 feature-text py-5 wow fadeIn" data-wow-delay="0.1s">
                <div class="p-lg-5 ps-lg-0">
                    <h6 class="text-primary">Why Choose Us!</h6>
                    <h1 class="mb-4">Complete Commercial & Residential Solar Systems</h1>
                    <p class="mb-4 pb-2">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam
                        amet
                        diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo erat
                        amet</p>
                    <div class="row g-4">
                        <div class="col-12 col-md-6">
                            <div class="d-flex align-items-center">
                                <div class="btn-lg-square bg-primary rounded-circle">
                                    <i class="fa fa-check text-white"></i>
                                </div>
                                <div class="ms-4">
                                    <p class="mb-0">Quality</p>
                                    <h5 class="mb-0">Services</h5>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="d-flex align-items-center">
                                <div class="btn-lg-square bg-primary rounded-circle">
                                    <i class="fa fa-user-check text-white"></i>
                                </div>
                                <div class="ms-4">
                                    <p class="mb-0">Expert</p>
                                    <h5 class="mb-0">Workers</h5>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="d-flex align-items-center">
                                <div class="btn-lg-square bg-primary rounded-circle">
                                    <i class="fa fa-drafting-compass text-white"></i>
                                </div>
                                <div class="ms-4">
                                    <p class="mb-0">Free</p>
                                    <h5 class="mb-0">Consultation</h5>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="d-flex align-items-center">
                                <div class="btn-lg-square bg-primary rounded-circle">
                                    <i class="fa fa-headphones text-white"></i>
                                </div>
                                <div class="ms-4">
                                    <p class="mb-0">Customer</p>
                                    <h5 class="mb-0">Support</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 pe-lg-0 wow fadeIn" data-wow-delay="0.5s" style="min-height: 400px;">
                <div class="position-relative h-100">
                    <img class="position-absolute img-fluid w-100 h-100" src="{% static 'brand/feature.jpg' %}"
                         style="object-fit: cover;" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

templates/theme/widgets/testimonials.html
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
            <h6 class="text-primary">Testimonial</h6>
            <h1 class="mb-4">What Our Clients Say!</h1>
        </div>
        <div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">
            {% for testimonial in testimonials %}
                <div class="testimonial-item text-center">
                    <div class="testimonial-img position-relative">
                        <img class="img-fluid rounded-circle mx-auto mb-5" src="{{ testimonial.image.url}}">
                        <div class="btn-square bg-primary rounded-circle">
                            <i class="fa fa-quote-left text-white"></i>
                        </div>
                    </div>
                    <div class="testimonial-text text-center rounded p-4">
                        <p>{{ testimonial.content }}</p>
                        <h5 class="mb-1">{{ testimonial.full_name }}</h5>
                        <span class="fst-italic">{{ testimonial.profession }}</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>